baseURL = 'https://blog.zhangjunbo.top/'
languageCode = 'zh-hans'
title = '那年夏天 宁静的海'
theme = "monochrome"
defaultContentLanguage = "zh-hans"
enableEmoji = true
paginate = 5

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
